(ns project-euler-clj.p2
  (:use clojure.test))

;; http://projecteuler.net

;; problem 2
;; Each new term in the Fibonacci sequence is generated by adding the previous two terms.
;; By starting with 1 and 2, the first 10 terms will be:
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;; By considering the terms in the Fibonacci sequence whose values do not
;; exceed four million, find the sum of the even-valued terms.

(defn p2 []
  (let
      [fib (map first
                (iterate
                 (fn [[x1 x2]] [x2 (+ x1 x2)])
                 [1 2]))]
    (apply + (filter even?
                     (take-while #(> 4000000 %) fib)))))
;; (p2) => 4613732
